### ISSUE TITLE
ServerBug · 16

### ISSUE THREAD

**Issue by linxi3380** [YingLunTown-DreamLand/DreamLand-YingLunTown#52]
Author - @linxi3380
Server - `Dreamland - Origin`
Level - `Normal`
Type - `Bug`
Num - `16`
***
经 `抽奖机` 处的地狱门 `传送` 后，`游戏模式` 切换存在刷屏情况，具体情况此图片。
***
![image](https://user-images.githubusercontent.com/122207897/230761559-d27510c1-831f-4853-aa44-625d5d2f8945.png)

**Comment by Happy2018new** [comment]
但是，我已经忘记这个屋子的坐标了

**Comment by Happy2018new** [comment]
Fixed, but not shown in this repository.
