### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by dfdsj100** [YingLunTown-DreamLand/DreamLand-YingLunTown#60]
如果玩家在游戏中改名，是否会影响地皮的进入、机器人的使用以及幻想币的数值（注：只是改名，不是换号）

**Comment by Happy2018new** [comment]
以下列出了目前仍受支持的地皮(领地)
- 全自动地皮 (通过主城 `NPC` 前往)
- 由管理组维护的人工地皮(领地)

对于前者(全自动地皮)，其基于计分板来验证地皮主的身份，而计分板上的分数不会随着玩家游戏昵称的改变而发生变化，这意味着在没有指令干预的情况下，地皮主身份不会随着游戏名称的改变而变更。

对于后者(由管理组维护的人工地皮/领地)，其基于单一的命令方块运作。这种地皮(领地)的命令方块被放置于命令区，并由管理组统一代管。这种地皮(领地)基于玩家游戏名称来验证地皮主的身份，这意味着地皮主在改名后将会丢失对地皮的访问权限。这并没有有效的解决办法，但地皮主可以通过向管理组更新名称数据以规避权限丢失的问题。

另，更改游戏昵称不会影响机器人的使用，幻想币数值也不会收到影响。
