### ISSUE TITLE
关于取消“全服最肝”在完结村附近设点的决定

### ISSUE THREAD

**Issue by dfdsj100** [YingLunTown-DreamLand/DreamLand-YingLunTown#63]
这些视频既是他设点的证据，也是他偷东西的证据，后续如果有我这边有什么破坏那么他可以算一个前科，或者说算一个嫌疑人

![99B1F118-A1EF-4A96-98DE-6967C76AC6E3](https://github.com/YingLunTown-DreamLand/DreamLand-YingLunTown/assets/159788551/3bfeb17b-cbe4-4da9-bf5b-f035bab37b02)
![F3C1D837-3942-478A-A558-0EA2FA9CD856](https://github.com/YingLunTown-DreamLand/DreamLand-YingLunTown/assets/159788551/7302366f-71fd-4d5f-8648-7e66cff91591)

**Comment by Happy2018new** [comment]
Related to #62

**Comment by Happy2018new** [comment]
你提交的是截图而非视频，请提交视频？

**Comment by Happy2018new** [comment]
[证据(视频)](https://drive.google.com/file/d/1OWI2_a8kXz4pStYlIwM6be9xh6D307de/view?usp=drive_link)

**Comment by Happy2018new** [comment]
该请求已被接受，相关信息详见 #62 ，此议题作为已完成而关闭。
