### ISSUE TITLE
回复

### ISSUE THREAD

**Issue by dfdsj100** [YingLunTown-DreamLand/DreamLand-YingLunTown#64]
这个是针对你前面所提问题的回复
![D759A7E9-5E1B-48D9-9D50-2F262A1A780E](https://github.com/YingLunTown-DreamLand/DreamLand-YingLunTown/assets/159788551/80417a1f-da20-41c0-82f8-61059c5463ff)
因为视频大小超过了10MB，所以我已经把视频发在了你的QQ私聊，完结村的坐标也发在了你的QQ私聊

**Comment by Happy2018new** [comment]
OK, I see that.

_Related to #62 and #63_
